name: Clash SpeedTest
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  speedtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install clash-speedtest
        run: go install github.com/faceair/clash-speedtest@latest

      - name: Run speed test
        run: |
          ~/go/bin/clash-speedtest -c 'https://raw.githubusercontent.com/go4sharing/sub/main/sub.yaml' -output sub.yaml -max-latency 2s -min-speed 5

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add sub.yaml
          git commit -m "update sub.yaml" || exit 0
          git push
