name: Clash SpeedTest
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  speedtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install clash-speedtest
        run: go install github.com/faceair/clash-speedtest@latest

      - name: Run clash-speedtest
        run: |
          ~/go/bin/clash-speedtest -c 'https://raw.githubusercontent.com/go4sharing/sub/main/sub.yaml' -output freesub.yaml -max-latency 2s -min-speed 5

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

          if git diff --quiet freesub.yaml; then
            echo "没有检测到变更，跳过提交"
            exit 0
          fi

          git add freesub.yaml
          git commit -m "update speedtest results"
          git push https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
