name: Clash SpeedTest

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  speedtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Go Cache Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-mods
          restore-keys: go-mods

      - name: Install clash-speedtest
        run: go install github.com/faceair/clash-speedtest@latest

      - name: Run clash-speedtest
        run: |
          ~/go/bin/clash-speedtest -c 'https://raw.githubusercontent.com/dongchengjie/airport/main/subs/merged/tested_within.yaml' -output fastsub.yaml -max-latency 2s -min-speed 5

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

          git add fastsub.yaml

          if git diff --cached --quiet; then
            echo "没有检测到变更，跳过提交"
            exit 0
          fi

          git commit -m "update speedtest results"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
